{{- if and .Values.nominatimApi.enabled (eq .Values.serviceType "ClusterIP") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "osm-seed.fullname" . }}-ingress-nominatim-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.ingress.cluster-issuer }}
    {{- if .Values.ingress.ingress-class -}}
    acme.cert-manager.io/http01-ingress-class: {{ .Values.ingress.ingress-class }}
    {{- end }}
spec:
  tls:
    - hosts:
      - nominatim.{{ .Values.domain }}
      secretName: {{ template "osm-seed.fullname" . }}-secret-nominatim

  rules:
  - host: nominatim.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "osm-seed.fullname" . }}-nominatim-api
            port:
              number: 80
{{- end }}